# Generated by Django 3.2.6 on 2021-09-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_login_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_user',
            old_name='username',
            new_name='user',
        ),
    ]
