# Generated by Django 3.2.6 on 2021-09-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_username_login_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_user',
            name='password',
        ),
    ]
